[package]
name = "mandelbrot2"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
image = "0.23.14"
piston = "0.53.0"
piston2d-graphics = "0.36.0"
piston_window = "0.116.0"
rayon = "1.5.1"
opencl3 = "0.6.0"
glutin = "0.30.0"
gl = "0.14.0"